package com.stapk.mobile.nativeadapter

import java.io.File

data class NativeAdapterPaths(private val filesDir: File) {
    val webDir: File = File(filesDir, "web")
    val webManifestFile: File = File(File(filesDir, "state"), "installed-web-manifest.json")
    val userConfigDir: File = File(filesDir, "user_config")
    val settingsFile: File = File(userConfigDir, "settings.json")
    val userProfileFile: File = File(userConfigDir, "user-profile.json")
    val providerConfigFile: File = File(userConfigDir, "provider-openai-compatible.json")
    val userDataDir: File = File(filesDir, "user_data")
    val exportsDir: File = File(userDataDir, "exports")
    val charactersDir: File = File(userDataDir, "characters")
    val chatsDir: File = File(userDataDir, "chats")
    val groupsDir: File = File(userDataDir, "groups")
    val groupChatsDir: File = File(userDataDir, "group_chats")
    val worldInfoDir: File = File(userDataDir, "world_info")
    val backgroundsDir: File = File(userDataDir, "backgrounds")
    val uploadsDir: File = File(userDataDir, "uploads")
    val userImagesDir: File = File(userDataDir, "user_images")
    val extensionsDir: File = File(userDataDir, "extensions")
    val imageMetadataFile: File = File(userDataDir, "image-metadata.json")
    val chatBackupsDir: File = File(userDataDir, "chat_backups")
    val statsFile: File = File(userDataDir, "stats.json")
    val personasDir: File = File(userDataDir, "personas")
    val presetsDir: File = File(userDataDir, "presets")
    val themesDir: File = File(userDataDir, "themes")
    val quickRepliesDir: File = File(userDataDir, "quick_replies")
    val movingUiDir: File = File(userDataDir, "moving_ui")
    val settingsBackupsDir: File = File(userConfigDir, "settings_backups")
    val quarantineDir: File = File(filesDir, "quarantine")
    val secretsDir: File = File(filesDir, "secrets")
    val logsDir: File = File(filesDir, "logs")
    val stateDir: File = File(filesDir, "state")
    val adapterStateFile: File = File(stateDir, "native-adapter-state.json")
    val extensionRegistryFile: File = File(stateDir, "extensions.json")
    val extensionTransactionFile: File = File(stateDir, "extension-transaction.json")
    val legacySillyTavernDir: File = File(filesDir, "SillyTavern")
}
